version: "3"

services: 
  app:
    environment: 
      PORT: ${APP_INTERNAL_PORT}
      MONGO_HOST:
      MONGO_PORT:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ${MONGO_VOLUME_DIR}:/data/db